services:
  newsportal.api:
    image: newsportal.api
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: NewsPortal.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"

